# Give a name to the workflow

name: First Workflow

# Define where it should be executed

on : workflow_dispatch

# Define jobs 

jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print salutations
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - good bye!"
